config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/iis:
      branch: master
      repo: https://github.com/openaire/iis
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/iis git:
        commands:
        - /usr/bin/env sh .sqa/script.thunder_meticulous_crocodile.sh
        container: qc.acc_gamboge_motivated_quail
  QC.Doc:
    repos:
      github.com/openaire/iis find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_worried_chinchilla.sh
        container: qc.doc_raspberry_dizzy_walrus
      github.com/openaire/iis git:
        commands:
        - /usr/bin/env sh .sqa/script.smoke_audacious_gerbil.sh
        container: qc.doc_harlequin_sarcastic_grasshopper
      github.com/openaire/iis markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bone_ambitious_octopus.sh
        container: qc.doc_wine_radiant_clownfish
  QC.Lic:
    repos:
      github.com/openaire/iis licensee:
        commands:
        - /usr/bin/env sh .sqa/script.turmeric_upbeat_boa.sh
        container: qc.lic_goldenrod_optimistic_shark
  QC.Sec:
    repos:
      github.com/openaire/iis bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_confused_turkey.sh
        container: qc.sec_cerulean_authentic_koala
  QC.Sty:
    repos:
      github.com/openaire/iis checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.salmon_easygoing_eel.sh
        container: qc.sty_snow_adventurous_dugong
      github.com/openaire/iis flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jet_innocent_platypus.sh
        container: qc.sty_carmine_quirky_piranha
      github.com/openaire/iis jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_eager_eel.sh
        container: qc.sty_boysenberry_energetic_chimpanzee
  QC.Uni:
    repos:
      github.com/openaire/iis pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ceru_elated_coyote.sh
        container: qc.uni_bone_timid_eel
  QC.Ver:
    repos:
      github.com/openaire/iis get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.champagne_upbeat_griffin.sh
        container: qc.ver_marina_vigilant_eel
timeout: 5400
